module.exports = {
	"invalid_sensor": "Ungültiger Sensor",
	"invalid_user": "Ungültiger Benutzer",
	"invalid_body": "Ungültiger Anfragenrumpf",
	"access_denied": "Zugriff verweigert",
	"missing_body": "Anfragenrumpf fehlt oder unvollständig",
	"missing_value": "Anfrage unvollständig",
	"db_updated": "Eintrag geändert",
	"db_deleted": "Eintrag gelöscht",
	"db_created": "Eintrag erstellt",
	"password_short": "Das Passwort muss mindestens 8 Zeichen besitzen",
	"invalid_confirmation": "Bestätigung der Authorisierung ungültig",
	"invalid_email": "E-mail Adresse ungültig",
	"user_email_exists": "Ein Nutzer mit dieser E-Mail existiert bereits!",
	"sensor_id_exists": "Ein Sensor mit diesem Namen existiert bereits",
	"logged_in": "Angemeldet",
	"logged_out": "Abgemeldet",
	"invalid_page": "Ungültige Seite",
	"something_broke": "Irgend etwas lief schief",
	"invalid_json": "JSON fehlerhaft",
	"invalid_coords": "Koordinaten Fehlerhaft",
	"map": "Karte",
	"user_area": "Mitgliederbereich",
	"about_area": "Mitmachen",
	"create_sensor": "Sensor erstellen",
	"longitude": "Längengrad",
	"latitude": "Breitengrad",
	"position": "Standort",
	"terms": "Ich habe die Nutzungsbedingunen gelesen und stimme diesen zu",
	"sensor_persistence": "Daten des Sensors werden selbst beim löschen des Users nicht gelöscht",
	"delete_user": "Nutzer löschen",
	"password": "Passwort",
	"confirm_delete": "Löschen bestätigen",
	"login": "Anmelden",
	"logout": "Abmelden",
	"update_user": "Nutzer ändern",
	"new_password": "Neues Passwort",
	"new_email": "Neue Email",
	"create_user": "Nutzer erstellen",
	"delete_sensor": "Sensor löschen",
	"sensor_management": "Sensorverwaltung",
	"change_sensor": "Bestehende Sensoren verwalten",
	"update_sensor": "Sensor updaten",
	"long_lat_info": "Höhen und Breitengrade können nicht geändert werden. Bitte lege einen neuen Sensor an falls sich die Position ändert",
	"sensor_name": "Sensorname",
	"prev_day": "Vorheriger Tag",
	"next_day": "Nächster Tag",
	"change_to_month": "Monatsanzeige",
	"download_as_csv": "Als CSV-Datei downloaden",
	"line_chart": "Liniendiagramm",
	"pie_chart": "Tortendiagramm",
};
