module.exports = {
	"invalid_sensor": "Invalid sensor",
	"invalid_user": "Invalid user",
	"invalid_body": "Invalid request body",
	"acces_denied": "Access denied",
	"missing_body": "No body specified",
	"missing_value": "Some values are missing",
	"db_updated": "Entry updated",
	"db_deleted": "Entry deleted",
	"db_created": "Entry created",
	"password_short": "The password has to be at least 8 characters long",
	"invalid_confirmation": "Invalid Confirmation",
	"invalid_email": "Please enter a valid email adress",
	"user_email_exists": "User with that email already exists",
	"sensor_id_exists": "Sensor with that ID already exists",
	"logged_in": "logged in",
	"logged_out": "logged out",
	"invalid_page": "Invalid Page",
	"something_broke": "Something broke!",
	"invalid_json": "Invalid JSON",
	"invalid_coords": "Coordinates not valid",
	"map": "Map",
	"user_area": "Users",
	"about_area": "About this Project",
	"longitude": "Longitude",
	"latitude": "Latitude",
	"position": "Environment",
	"terms": "I have read the terms and conditions",
	"sensor_persistence": "Deleting the sensor does not delete the produced Data",
	"delete_user": "Delete User",
	"password": "Password",
	"confirm_delete": "Confirm Deletion",
	"login": "Login",
	"logout": "Logout",
	"update_user": "Update User",
	"new_password": "New Password",
	"new_email": "New Email",
	"create_user": "Create User",
	"delete_sensor": "Delete Sensor",
	"sensor_management": "Sensor Management",
	"change_sensor": "Manage existing Sensors",
	"update_sensor": "Update Sensor",
	"long_lat_info": "Longitude and Latitude can't be changed. If the Position changes pls add a new Sensor",
	"sensor_name": "Sensorname",
	"prev_day": "Previous day",
	"next_day": "Next day",
	"change_to_month": "Change to month scale",
	"download_as_csv": "Download as CSV file",
	"line_chart": "Line chart",
	"pie_chart": "Pie chart",
	"create_sensor": "Create sensor"
};
